# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'decisionJamMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for decisionJamMobile
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'decisionJamMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'decisionJamMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for decisionJamMobile-tvOS

  target 'decisionJamMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
